from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(838, 640)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow2.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(370, 145, 75, 23))
        self.start.setObjectName("start")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 196, 221, 16))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 203, 221, 16))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 246, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 276, 71, 16))
        self.label_4.setObjectName("label_4")
        self.r2 = QtWidgets.QLabel(self.centralwidget)
        self.r2.setGeometry(QtCore.QRect(120, 248, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.r2.setFont(font)
        self.r2.setObjectName("r2")
        self.rms = QtWidgets.QLabel(self.centralwidget)
        self.rms.setGeometry(QtCore.QRect(120, 276, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rms.setFont(font)
        self.rms.setObjectName("rms")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 316, 151, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(210, 175, 431, 20))
        self.label_6.setObjectName("label_6")
        self.out_image = QtWidgets.QLabel(self.centralwidget)
        self.out_image.setGeometry(QtCore.QRect(30, 346, 341, 221))
        self.out_image.setText("")
        self.out_image.setPixmap(QtGui.QPixmap("New\\RC_1.svg"))
        self.out_image.setScaledContents(True)
        self.out_image.setObjectName("out_image")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 577, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(490, 243, 151, 16))
        self.label_8.setObjectName("label_8")
        self.out_table = QtWidgets.QTableWidget(self.centralwidget)
        self.out_table.setGeometry(QtCore.QRect(410, 273, 381, 121))
        self.out_table.setAutoFillBackground(True)
        self.out_table.setInputMethodHints(QtCore.Qt.ImhNone)
        self.out_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.out_table.setObjectName("out_table")
        self.out_table.setColumnCount(3)
        self.out_table.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.out_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.out_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.out_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(100, 100, 200))
        self.out_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.out_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.out_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.out_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(100, 50, 50))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.out_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.out_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.out_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.out_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.out_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.out_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.out_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.out_table.setItem(2, 2, item)
        self.out_table.horizontalHeader().setDefaultSectionSize(90)
        self.out_table.horizontalHeader().setHighlightSections(True)
        self.out_table.horizontalHeader().setMinimumSectionSize(36)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(410, 433, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(410, 473, 71, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(410, 513, 71, 16))
        self.label_11.setObjectName("label_11")
        self.accuracy = QtWidgets.QLabel(self.centralwidget)
        self.accuracy.setGeometry(QtCore.QRect(490, 435, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.accuracy.setFont(font)
        self.accuracy.setObjectName("accuracy")
        self.sensitivity = QtWidgets.QLabel(self.centralwidget)
        self.sensitivity.setGeometry(QtCore.QRect(490, 473, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sensitivity.setFont(font)
        self.sensitivity.setObjectName("sensitivity")
        self.specificity = QtWidgets.QLabel(self.centralwidget)
        self.specificity.setGeometry(QtCore.QRect(490, 513, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.specificity.setFont(font)
        self.specificity.setObjectName("specificity")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(550, 434, 111, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(550, 471, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(550, 510, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(20, 10, 341, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(20, 120, 101, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(256, 120, 481, 20))
        self.label_17.setObjectName("label_17")
        self.filename = QtWidgets.QLineEdit(self.centralwidget)
        self.filename.setGeometry(QtCore.QRect(120, 120, 121, 20))
        self.filename.setObjectName("filename")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(390, 200, 20, 391))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(15, 30, 801, 71))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(14)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget.setItem(0, 13, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(70)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(20, 100, 491, 16))
        self.label_18.setObjectName("label_18")
        MainWindow2.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow2)
        self.statusbar.setObjectName("statusbar")
        MainWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "NKR_Ortho_Tool_1.v2.0: Test Your Own Data"))
        self.start.setText(_translate("MainWindow2", "Start Test"))
        self.label.setText(_translate("MainWindow2", "Results for Constant Score Prediction:"))
        self.label_2.setText(_translate("MainWindow2", "Results for Poor Outcome Prediction:"))
        self.label_3.setText(_translate("MainWindow2", "R^2 Value:"))
        self.label_4.setText(_translate("MainWindow2", "RMS Error:"))
        self.r2.setText(_translate("MainWindow2", "0.00"))
        self.rms.setText(_translate("MainWindow2", "100.00"))
        self.label_5.setText(_translate("MainWindow2", "Test Performance graph:"))
        self.label_6.setText(_translate("MainWindow2", "(Testing on models trained based on the data provided by Gavaskar et al)"))
        self.label_7.setText(_translate("MainWindow2", "More the points are closer to the diagonal line, better the performance."))
        self.label_8.setText(_translate("MainWindow2", "Confusion matrix:"))
        item = self.out_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow2", "Predicted Poor Outcome"))
        item = self.out_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow2", "Predicted Good Outcome"))
        item = self.out_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow2", "Total"))
        item = self.out_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow2", "Actual Poor Outcome"))
        item = self.out_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow2", "Actual Good Outcome"))
        item = self.out_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow2", "Total"))
        __sortingEnabled = self.out_table.isSortingEnabled()
        self.out_table.setSortingEnabled(False)
        item = self.out_table.item(0, 0)
        item.setText(_translate("MainWindow2", "1,1"))
        item = self.out_table.item(0, 1)
        item.setText(_translate("MainWindow2", "1,2"))
        item = self.out_table.item(0, 2)
        item.setText(_translate("MainWindow2", "1,3"))
        item = self.out_table.item(1, 0)
        item.setText(_translate("MainWindow2", "2,1"))
        item = self.out_table.item(1, 1)
        item.setText(_translate("MainWindow2", "2,2"))
        item = self.out_table.item(1, 2)
        item.setText(_translate("MainWindow2", "2,3"))
        item = self.out_table.item(2, 0)
        item.setText(_translate("MainWindow2", "3,1"))
        item = self.out_table.item(2, 1)
        item.setText(_translate("MainWindow2", "3,2"))
        item = self.out_table.item(2, 2)
        item.setText(_translate("MainWindow2", "3,3"))
        self.out_table.setSortingEnabled(__sortingEnabled)
        self.label_9.setText(_translate("MainWindow2", "Accuracy:"))
        self.label_10.setText(_translate("MainWindow2", "Sensitivity:"))
        self.label_11.setText(_translate("MainWindow2", "Specificity:"))
        self.accuracy.setText(_translate("MainWindow2", "95%"))
        self.sensitivity.setText(_translate("MainWindow2", "85%"))
        self.specificity.setText(_translate("MainWindow2", "100%"))
        self.label_12.setText(_translate("MainWindow2", "(R^2 value X 100)"))
        self.label_13.setText(_translate("MainWindow2", "(Actual poor outcome predicted/ Total poor outcome) X 100)"))
        self.label_14.setText(_translate("MainWindow2", "(Actual good outcome predicted/Total good outcome) X 100)"))
        self.label_15.setText(_translate("MainWindow2", "Format for Input Data (Input data must be in .csv format):"))
        self.label_16.setText(_translate("MainWindow2", "Input filename:"))
        self.label_17.setText(_translate("MainWindow2", "(Please copy the input data file in the same folder where this app file (.exe) is present.)"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow2", "Values"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow2", "Sl No"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow2", "Age"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow2", "Sex"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow2", "Fracture -Type"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow2", "Fracture - Type"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow2", "Smoking"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow2", "Backbleeding"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow2", "Capsule att"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow2", "PM spike"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow2", "Headheight"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow2", "Handedness"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow2", "MOV"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow2", "Constant Score"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow2", "Outcome"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow2", "Integers"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow2", "Positive real number"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow2", "male=0, female=1"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow2", "anterior=0, posterior=1"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow2", "   3 part=0,           4 part=1"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("MainWindow2", "No =0, Yes =1"))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("MainWindow2", "Yes=0, No=1"))
        item = self.tableWidget.item(0, 7)
        item.setText(_translate("MainWindow2", "Yes=0, No=1"))
        item = self.tableWidget.item(0, 8)
        item.setText(_translate("MainWindow2", "Yes=0, No=1"))
        item = self.tableWidget.item(0, 9)
        item.setText(_translate("MainWindow2", ">2mm=0,  <2mm=1"))
        item = self.tableWidget.item(0, 10)
        item.setText(_translate("MainWindow2", "Dominant=0, Non-domnt=1"))
        item = self.tableWidget.item(0, 11)
        item.setText(_translate("MainWindow2", "High=0, Low=1"))
        item = self.tableWidget.item(0, 12)
        item.setText(_translate("MainWindow2", "Real number"))
        item = self.tableWidget.item(0, 13)
        item.setText(_translate("MainWindow2", "Good=0, Poor=1"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_18.setText(_translate("MainWindow2", "*poor outcome includes: Constant score<55, Non-union, AVN and Revision surgery."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow2 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow2)
    MainWindow2.show()
    sys.exit(app.exec_())
